[build]
  functions = "netlify/functions"
  publish = "public"  # atau "." jika file HTML kamu di root

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
